---
services:
  db:
    image: postgres:18
    container_name: stock-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-stockdb}
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
