---
services:
  db:
    image: postgres:18
    container_name: stock-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-stockdb}
    volumes:
      - db_data:/var/lib/postgresql

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-stock
    volumes:
      - "pgadmin-stock-data:/var/lib/pgadmin"
    ports:
      - "5532:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=admin@schreibernet.dev

volumes:
  db_data:
  pgadmin-stock-data:
