// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           uuid.UUID          `json:"id"`
	Brand        string             `json:"brand"`
	Name         string             `json:"name"`
	Subtype      string             `json:"subtype"`
	Aliases      []string           `json:"aliases"`
	DefaultPrice pgtype.Numeric     `json:"default_price"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
