// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (brand, name, subtype, aliases, default_price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, brand, name, subtype, aliases, default_price, created_at, updated_at
`

type CreateProductParams struct {
	Brand        string         `json:"brand"`
	Name         string         `json:"name"`
	Subtype      string         `json:"subtype"`
	Aliases      []string       `json:"aliases"`
	DefaultPrice pgtype.Numeric `json:"default_price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Brand,
		arg.Name,
		arg.Subtype,
		arg.Aliases,
		arg.DefaultPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.Subtype,
		&i.Aliases,
		&i.DefaultPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, brand, name, subtype, aliases, default_price, created_at, updated_at FROM products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Name,
			&i.Subtype,
			&i.Aliases,
			&i.DefaultPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, brand, name, subtype, aliases, default_price, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.Subtype,
		&i.Aliases,
		&i.DefaultPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
